=head1 Installing Perlbal

This document describes the steps, dependencies and requirements to install Perlbal.


=head2 Installing Perlbal for the impatient

    $ perl -MCPAN -e shell

    cpan> install Perlbal


=head2 Installing Perlbal (with a little more detail)

You need to have perl on the machine. You can grab it from http://www.perl.org/.

Having perl on the machine should give you access to the CPAN shell, one of several possible ways to install and upgrade Perl modules.

Start your CPAN shell:

    $ perl -MCPAN -e shell

And now tell it to install Perlbal:

    cpan> install Perlbal

In the end you should see a message stating "make install  -- OK" (if you don't, please refer to section Troubleshooting later in this document).


=head2 Optional Dependencies and Assyncronous IO

Perlbal checks for IO::AIO availability and uses it to perform assynchronous IO operations. If you're performing disk operations (e.g., using Perlbal as a web server), having IO::AIO will improve your response times.

The only thing required in order to benefit from this feature is to install IO::AIO:

    $ perl -MCPAN -e shell

    cpan> install IO::AIO

If you don't have IO::AIO installed a warning message will be displayed when you start perlbal:

    WARNING:  AIO mode disabled or not available.  
              Perlbal will run slowly under load if you're doing any
              disk operations. (e.g. web_server mode).
              Install IO::AIO for better performance.


=head2 Troubleshooting

=head3 No compiler available

If there's no compiler available on the machine you will probably see an error ending in something like:

    Failed during this command:
     DORMANDO/Perlbal-X.XX.tar.gz : writemakefile NO '/usr/bin/perl Makefile.PL INSTALLDIRS=site' returned status -1

You need to install something like C<gcc> (check http://gcc.gnu.org/).

After installing C<gcc>, when trying to install Perlbal again you may get another error message:

    cpan> install Perlbal
    Running install for module 'Perlbal'
    Running make for D/DO/DORMANDO/Perlbal-X.XX.tar.gz
      Has already been unwrapped into directory /home/myself/.cpan/build/Perlbal-X.XX-GFko0J
      '/usr/bin/perl Makefile.PL INSTALLDIRS=site' returned status -1, won't make
    Running make test
      Make had some problems, won't test
    Running make install
      Make had some problems, won't install

This is the cpan shell assuming nothing changed in the system and skipping a few steps. You need to let it know you're willing to forget the past:

    cpan> look Perlbal

    $ rm -rf *
    
    $ exit

And now you can try installation again:

    cpan> install Perlbal




