
=head1 Project Title

=over 1

=item Name:

Name of proposer.

=item Email:

Where we can contact you!

=item Amount Requested:

How much is your project worth?

=back

=head2 Synopsis

A short description.

=head2 Benefits to the Perl Community

Why should the Perl Community grant this project?

=head2 Deliverables

Quantifiable results e.g. "Improve X modules in ways Y and Z",
"Write 3 articles for X website".

=head2 Project Details

A more detailed description.

If you aren't the primary maintainer of the project you want funding
for, show that you have approval from the primary maintainer.

=head2 Inch-stones

If your grant is going to take longer than a week it's useful to break
down your project into small chunks. This helps everybody track of
progress, and lets you see if your project schedule is practical!

Try and think in "inch-stones" rather than "mile-stones". Breaking down
your grant into many small goals makes it harder to overlook
difficulties, and easier to see progress as you complete your grant.

=head2 Project Schedule

How long will the project take? When can you begin work?

=head2 Completeness Criteria

Describe how your grant can be evaluated. For instance, code will be
merged in Perl tree, or a module will be released to CPAN with the
specified features, etc.

=head2 Bio

Who are you? What makes you the best person to work on this project?

=cut
