=head1 NAME

Perlbal::Manual::Configuration - How to configure Perlbal


=head2 VERSION

This document refers to Perlbal 1.76.


=head2 Using a configuration file

By default, perlbal looks for a configuration file at C</etc/perlbal/perlbal.conf>.

You can also point perlbal at a different configuration file with the -c flag.

    $ perlbal -c /home/user/perlbal.conf


=head2 Configuration file

A C<Perlbal>'s configuration file is a text file where you create pools and services, add servers to pools, set services' parameters and enable/disable services.

Indentation is not mandatory, but it's considered a good practice for readability issues.

Configuration is case insensitive, but it's also a good practice to uppercase all directives.


=head3 Pools

Here's a sample configuration of a pool:

    CREATE POOL mywebsite
        POOL mywebsite ADD 10.0.0.1:80
        POOL mywebsite ADD 10.0.0.2:80

The first line creates a pool called C<mywebsite>. The second and third lines add two different servers to that pool.

From here on you'll be able to use this pool in a service.

Also, note that right after creating the pool, you don't need to specify which pool you're adding servers to, as it is considered to be the active pool:

    CREATE POOL mywebsite
        POOL ADD 10.0.0.1:80
        POOL ADD 10.0.0.2:80


=head4 Configuring a pool in a separate file

You can create a pool in a separate file by using the C<nodefile> parameter:

    CREATE POOL dynamic
        SET nodefile = conf/nodelist.dat

This separate file should contain IP addresses, one per line (empty lines are ignored, as well as comments started by the L<#> sign).

Check C<conf/load-balancer.conf> and C<conf/nodelist.dat> for an example.


=head3 Services

Here's a sample service:

    CREATE SERVICE service_mywebsite
        SET role            = reverse_proxy
        SET pool            = mywebsite
        SET listen          = 10.0.0.3:80

The first line creates a service called C<service_mywebsite>.

On the three following lines we are setting up three parameters for that service (you can see this same example in C<Perlbal::Manual::LoadBalancer> in more detail).


=head3 Setting parameters

You can set parameters via commands of either forms:

    SET <service-name> <param> = <value>
    SET <param> = <value>

For a full list of parameters see C<Perlbal::Manual::LoadBalancer>, C<Perlbal::Manual::ReverseProxy> or C<Perlbal::Manual::WebServer>.


=head4 B<Note on types>:

'bool' values can be set using one of 1, true, yes, on, 0, false, off, or no.

'size' values are in integer bytes, or an integer followed by 'b', 'k', or 'm' (case-insensitive) for bytes, KiB, or MiB.


=head3 Enabling/Disabling services

To enable a service:

    ENABLE service_mywebsite

To disable a service:

    DISABLE service_mywebsite

The lines is what allows you to have several services configured in a file even if they are not currently active (a common scenario is to configure everything on the file and then enable/disable services on-the-fly as required; see C<Perlbal::Manual::Management> for more information on this process).


=head3 Including configuration files

While Perlbal doesn't natively let you include a configuration file within another, one of its core Plugins does.

By using C<Perlbal::Plugin::Include> you can use this feature:

    LOAD include
    INCLUDE = /etc/perlbal/my.conf
    INCLUDE = /etc/perlbal/other.conf /etc/perlbal/*.conf

See C<Perlbal::Plugin::Include> for further examples and more information.


=head3 Comments

Comments in C<Perlbal>'s configuration files start with a C<#>:

    # this is a comment
    ENABLE myservice # this is also a comment


=head2 Environment variables

=head3 DANGABUILD_DAEMONONLY

Used in C<Makefile.PL>. If set to a true value the modules will not be built.


=head3 DANGABUILD_MODULESONLY

Used in C<Makefile.PL>. If set to a true value only the modules will be built, not the C<perlbal> executable.


=head3 PERLBAL_DEBUG

There are four levels of debugging in Perlbal.

By setting this variable to a value between 0 and 4 (included) you will activate Perbal's debug.

    PERLBAL_DEBUG = 0 # no debug
    
    PERLBAL_DEBUG = 4 # debug everything


=head3 PERLBAL_DEBUG_BUFFERED_UPLOADS

By setting this variable to 1 you can tell Perlbal to add a C<X-PERLBAL-BUFFERED-UPLOAD-REASON> header to requests that have to be buffered.

This can be useful to let your backend machine know that Perlbal is buffering the request.

The value of the header contains the reason why the request was buffered.


=head3 PERLBAL_DEBUG_OBJ

This is the variable you'll have to set to a true value in order to properly use the commands C<obj>, C<track> and C<varsize>.

You will also need to set C<PERLBAL_TRACK_STATES> to a true value (see below).


=head3 PERLBAL_TEST_ALPHA

This is a variable used to test C<Perlbal>'s alpha features.

If you're a developer working on one of these features, first set the variable to a true value:

    PERLBAL_TEST_ALPHA = 1

And then, on your test file, use something like:

    unless ($ENV{PERLBAL_TEST_ALPHA}) {
        plan skip_all => 'Alpha feature; test skipped without $ENV{PERLBAL_TEST_ALPHA}';
        exit 0;
    } else {
        plan tests => 4;
    }


=head3 PERLBAL_TRACK_STATES

This is the variable you'll have to set to a true value in order to properly use the commands C<state changes> and C<varsize>.

For the command C<varsize> you will also need to set C<DEBUG_OBJ> to a true value (see above).

See C<Perlbal::Manual::Management> for more information.


=head3 PERLBAL_XS_HEADERS

By setting to a true value you can enable C<Perlbal::XS::HTTPHeaders>, if installed.


=head3 TEST_PERLBAL_FOREGROUND

This variable is used by C<Perlbal::Test> to test Perlbal.

C<TEST_PERLBAL_FOREGROUND> with a true value tells C<Perlbal::Test> that it should run a server in the foreground.

See C<Perlbal::Test> for more information.


=head3 TEST_PERLBAL_USE_EXISTING

This variable is used by C<Perlbal::Test> to test Perlbal.

If C<TEST_PERLBAL_USE_EXISTING> is set to a true value then a socket will be returned which is connected to an existing server's management port.

See C<Perlbal::Test> for more information.


=head2 Setting up Perlbal

You can run C<perlbal> as a daemon:

    $ perlbal --daemon -c /home/user/perlbal.conf

A common practice is to create a C<perlbal.sh> file that supports the common operations you'll require (start, stop, restart) and place it under C</etc/init.d>.


=head2 SEE ALSO

C<Perlbal::Manual::Management>.
