=head1 NAME

Perlbal::Manual::Selector - Configuring Perlbal as a virtual service that maps onto other services


=head2 VERSION

This document details selector configuration of Perlbal 1.76.


=head2 READ ME FIRST

Please refer to C<Perlbal::Manual::Configuration> for a better explanation on how to configure Perlbal. This file will make much more sense after reading that.


=head2 Configuring Perlbal as a Selector

The C<selector> role allows you to create a service that selects to which service a request should be sent to.

Here's an example of how to do that with the help of C<Perlbal::Plugin::VHosts>:

    LOAD vhosts

    CREATE SERVICE selector_service
      SET listen         = 0.0.0.0:80
      SET role           = selector
      SET plugins        = vhosts

      VHOST *.site1.com  = service1
      VHOST *.site2.com  = service2
    ENABLE selector_service

In this case, requests to both C<site1> and C<site2> are received by C<selector_service>, which then sends requests for C<site1> to C<service1> and likewise for C<site2> and C<service2>.
